# NUMPY

KEYNOTE 1:
import numpy as np

KEYNOTE 2: Generating random data

In [2]:
import numpy as np
np.random.rand(2,3)
# Could also be written with a variable
# data=np.random.rand(2,3)

array([[0.28301241, 0.58104052, 0.2678254 ],
       [0.40369631, 0.11830858, 0.77678173]])

In [8]:
# data manipulation of this data is possible i.e
data=np.random.rand(2,3)
data

array([[0.80860582, 0.77361852, 0.29286614],
       [0.50510516, 0.2249013 , 0.71674439]])

In [9]:
data+data

array([[1.61721163, 1.54723703, 0.58573228],
       [1.01021031, 0.4498026 , 1.43348877]])

In [10]:
data*10

array([[8.08605817, 7.73618517, 2.92866138],
       [5.05105155, 2.24901299, 7.16744386]])

KEYNOTE 3:
    Creating ndarray

In [17]:
# done by use of array function
import numpy as np
value=[1,2,3,5.6,7]
myarr = np.array(value)
myarr

array([1. , 2. , 3. , 5.6, 7. ])

In [22]:
# inspecting the array
myarr.ndim

1

In [21]:
myarr.shape

(5,)

In [23]:
myarr.dtype

dtype('float64')

In [27]:
np.arange(3,7)

array([3, 4, 5, 6])

In [28]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
# create a N by N matrix
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [35]:
np.empty((2,2))

array([[1., 0.],
       [0., 0.]])

In [37]:
# creating an array and changing its data type
value1=np.array([1,2,3],dtype=np.float64)

In [38]:
value1.dtype

dtype('float64')

In [39]:
# POINT TO NOTE: string in numpy is written as string_

KEYNOTE 4:
    Indexing and slicing

In [42]:
index=np.arange(10)
index

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
value_index=index[4:7]
value_index

array([19, 19, 19])

In [49]:
value_index=19
index

array([ 0,  1,  2,  3, 19, 19, 19,  7,  8,  9])

In [55]:
val=np.ones((2,3,4))
val

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [58]:
val[:2,2]=10
val

array([[[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [10., 10., 10., 10.]],

       [[ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [10., 10., 10., 10.]]])

KEYNOTE 5:
    Boolen indexing

In [67]:
stringvalue=np.array(['good','best','jovial','great'])
stringvalue

array(['good', 'best', 'jovial', 'great'], dtype='<U6')

In [62]:
numvalue=np.random.rand(4,3)
numvalue

array([[0.33031956, 0.70597522, 0.22382233],
       [0.9172698 , 0.03978493, 0.81400453],
       [0.67917089, 0.9260663 , 0.20275909],
       [0.22840632, 0.10178671, 0.34355441]])

In [68]:
stringvalue=='good'

array([ True, False, False, False])

In [69]:
numvalue[stringvalue=='good']

array([[0.33031956, 0.70597522, 0.22382233]])

KEYNOTE 6:Facial indexing

In [73]:
arra=np.empty((7,3))
arra

array([[ 1.49514843e-311,  1.49511800e-311,  1.00918785e+161],
       [ 1.49514843e-311,  1.49511800e-311, -1.26724393e+028],
       [ 1.49514843e-311,  1.49511796e-311,  1.60968008e-295],
       [ 1.49514843e-311,  1.49511796e-311, -8.34725476e-171],
       [ 1.49514843e-311,  1.49511857e-311,  2.01163299e-004],
       [ 1.49514843e-311,  1.49511857e-311,  8.24762968e+273],
       [ 1.49514843e-311,  1.49511796e-311,  1.72719574e-249]])

In [74]:
for i in range(7):
    arra[i]=i
arra

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.],
       [5., 5., 5.],
       [6., 6., 6.]])

In [75]:
# use of reshape function
ar=np.arange(10).reshape(5,2)
ar

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

Other fuctionalities under numpy:

In [78]:
np.sqrt(10)

3.1622776601683795

In [79]:
remainder,whole_part=np.modf(3.123)

In [80]:
remainder

0.12300000000000022

In [81]:
whole_part

3.0

In [82]:
np.abs(12.45)

12.45

In [3]:
import numpy as np
x=np.random.rand(4)
y=np.random.rand(4)
z=np.maximum(x,y)
z

array([0.46095067, 0.73203105, 0.66426164, 0.51989262])

In [5]:
w=np.exp(2)
w

7.38905609893065

In [8]:
# BINARY UNARY FUCTION:
# add Add corresponding elements in arrays
# subtract Subtract elements in second array from first array
# multiply Multiply array elements
# divide, floor_divide Divide or „oor divide (truncating the remainder)
# power Raise elements in first array to powers indicated in second array
# maximum, fmax Element-wise maximum; fmax ignores NaN
# minimum, fmin Element-wise minimum; fmin ignores NaN
# mod Element-wise modulus (remainder of division)
# copysign Copy sign of values in second argument to values in first argument

# UNARY FUNCTION
# abs, fabs Compute the absolute value element-wise for integer, „oating-point, or complex values
# sqrt Compute the square root of each element (equivalent to arr ** 0.5)
# square Compute the square of each element (equivalent to arr ** 2)
# exp Compute the exponent ex
#  of each element
# log, log10,
# log2, log1p
# Natural logarithm (base e), log base 10, log base 2, and log(1 + x), respectively
# sign Compute the sign of each element: 1 (positive), 0 (zero), or –1 (negative)
# ceil Compute the ceiling of each element (i.e., the smallest integer greater than or equal to that
# number)
# floor Compute the „oor of each element (i.e., the largest integer less than or equal to each element)
# rint Round elements to the nearest integer, preserving the dtype
# modf Return fractional and integral parts of array as a separate array
# isnan Return boolean array indicating whether each value is NaN (Not a Number)
# isfinite, isinf Return boolean array indicating whether each element is finite (non-inf, non-NaN) or infinite,
# respectively
# cos, cosh, sin,
# sinh, tan, tanh
# Regular and hyperbolic trigonometric functions
# arccos, arccosh,
# arcsin, arcsinh,
# arctan, arctanh
# Inverse trigonometric functions
# logical_not Compute truth value of not x element-wise (equivalent to ~arr).

# ARRAY CREATING FUNCTIONS
# array Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a dtype
# or explicitly specifying a dtype; copies the input data by default
# asarray Convert input to ndarray, but do not copy if the input is already an ndarray
# arange Like the built-in range but returns an ndarray instead of a list
# ones,
# ones_like
# Produce an array of all 1s with the given shape and dtype; ones_like takes another array and
# produces a ones array of the same shape and dtype
# zeros,
# zeros_like
# Like ones and ones_like but producing arrays of 0s instead
# empty,
# empty_like
# Create new arrays by allocating new memory, but do not populate with any values like ones and
# zeros
# full,
# full_like
# Produce an array of the given shape and dtype with all values set to the indicated “fill value”
# full_like takes another array and produces a filled array of the same shape and dtype
# eye, identity Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere)


In [9]:
import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
c=x[:2,1:]
c

array([[2, 3],
       [5, 6]])